/***************************************************/
/**       AFE Sequence Helper version 0.100.0       **/
/**            Thu Apr 05 18:34:04 2018           **/
/***************************************************/

/**
 ** Copyright (C) 2014 Analog Devices Inc., All Rights Reserved.
 **
 **
 ** This file was generated automatically based upon the input to the AFE Sequence Helper.
 ** It may be preferable to change the AFE Sequence Helper input rather than editing this file directly.
 **
 **
 ** THIS SOFTWARE IS PROVIDED BY ANALOG DEVICES, INC. AND CONTRIBUTORS "AS IS" AND ANY
 ** EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, NON-INFRINGEMENT,
 ** TITLE, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
 ** NO EVENT SHALL ANALOG DEVICES, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 ** INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE OR CONSEQUENTIAL DAMAGES
 ** (INCLUDING, BUT NOT LIMITED TO, DAMAGES ARISING OUT OF CLAIMS OF INTELLECTUAL
 ** PROPERTY RIGHTS INFRINGEMENT; PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 ** OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 ** THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 ** NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 ** EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 **/

const uint32_t seq_afe_ampmeas[] = {

    0x000D004A,    /* Safety word: command count = 31:16, CRC = 7:0 */
    0x84007818,    /* AFE_FIFO_CFG: DATA_FIFO_SOURCE_SEL = 3, DATA_FIFO_DMA_REQ_EN = 1, DATA_FIFO_EN = 1, DATA_FIFO_THR_VAL = 0, CMD_FIFO_DMA_REQ_EN = 1, CMD_FIFO_EN = 1, CMD_FIFO_THR_VAL = 0 */
    0xA000001E,    /* AFE_ADC_CFG: GAIN_OFFS_SEL = 0, REFEXCITESW_EN = 0, MUX_SEL = 30 */
    0xA2000000,    /* AFE_SUPPLY_LPF_CFG: BYPASS_SUPPLY_LPF = 0 */
    0x86000640,    /* AFE_SW_CFG: SW_SOURCE_SEL = 0, IVS_STATE = 0, TMUX_STATE = 0, NMUX_STATE = 6, PMUX_STATE = 4, DMUX_STATE = 0 */
    0x00109A00,    /* Wait: 68.0 ms */
    0x800000B0,    /* AFE_CFG: ALDOILIMIT_EN = 0, VREFBUFILIMIT_EN = 0, VBIASBUF_EN = 0, SUPPLY_LPF_EN = 0, DFT_EN = 0, WAVEGEN_EN = 0, TEMP_CONV_EN = 0, TEMP_SENSOR_EN = 0, TIA_EN = 0, INAMP_EN = 0, BUF_EN = 0, ADC_CONV_EN = 0, ADC_EN = 1, DAC_EN = 0, REF_EN = 1, ALDO_EN = 1 */
    0x00000C80,    /* Wait: 0.2 ms */
    0x800001B0,    /* AFE_CFG: ALDOILIMIT_EN = 0, VREFBUFILIMIT_EN = 0, VBIASBUF_EN = 0, SUPPLY_LPF_EN = 0, DFT_EN = 0, WAVEGEN_EN = 0, TEMP_CONV_EN = 0, TEMP_SENSOR_EN = 0, TIA_EN = 0, INAMP_EN = 0, BUF_EN = 0, ADC_CONV_EN = 1, ADC_EN = 1, DAC_EN = 0, REF_EN = 1, ALDO_EN = 1 */
    0x00090880,    /* Wait: 37.0 ms */
    0x86010640,    /* AFE_SW_CFG: SW_SOURCE_SEL = 0, IVS_STATE = 1, TMUX_STATE = 0, NMUX_STATE = 6, PMUX_STATE = 4, DMUX_STATE = 0 */
    0x86000640,    /* AFE_SW_CFG: SW_SOURCE_SEL = 0, IVS_STATE = 0, TMUX_STATE = 0, NMUX_STATE = 6, PMUX_STATE = 4, DMUX_STATE = 0 */
    0x800000B0,    /* AFE_CFG: ALDOILIMIT_EN = 0, VREFBUFILIMIT_EN = 0, VBIASBUF_EN = 0, SUPPLY_LPF_EN = 0, DFT_EN = 0, WAVEGEN_EN = 0, TEMP_CONV_EN = 0, TEMP_SENSOR_EN = 0, TIA_EN = 0, INAMP_EN = 0, BUF_EN = 0, ADC_CONV_EN = 0, ADC_EN = 1, DAC_EN = 0, REF_EN = 1, ALDO_EN = 1 */
    0x82000002,    /* AFE_CFG: ALDOILIMIT_EN = 0, VREFBUFILIMIT_EN = 0, VBIASBUF_EN = 1, SUPPLY_LPF_EN = 0, DFT_EN = 0, WAVEGEN_EN = 0, TEMP_CONV_EN = 0, TEMP_SENSOR_EN = 0, TIA_EN = 1, INAMP_EN = 1, BUF_EN = 1, ADC_CONV_EN = 0, ADC_EN = 1, DAC_EN = 1, REF_EN = 1, ALDO_EN = 1 */
};

